# Normal vs. Keloids
printf "\"ids\",\"type\",\"path\"\n\"HDF1\",\"Normal\",\"/gpfs/research/medicine/sequencer/NovaSeq/Outputs_fastq/2020_Outputs/Akash_Gunjan_05-19-2020_Yuna-samples/HISAT2/expression/stringtie/ref_only/HDF1_UT\"\n\"HDF2\",\"Normal\",\"/gpfs/research/medicine/sequencer/NovaSeq/Outputs_fastq/2020_Outputs/Akash_Gunjan_05-19-2020_Yuna-samples/HISAT2/expression/stringtie/ref_only/HDF2_UT\"\n\"HDF3\",\"Normal\",\"/gpfs/research/medicine/sequencer/NovaSeq/Outputs_fastq/2020_Outputs/Akash_Gunjan_05-19-2020_Yuna-samples/HISAT2/expression/stringtie/ref_only/HDF3_UT\"\n\"HDFPA\",\"Normal\",\"/gpfs/research/medicine/sequencer/NovaSeq/Outputs_fastq/2020_Outputs/Akash_Gunjan_05-19-2020_Yuna-samples/HISAT2/expression/stringtie/ref_only/HDFPA_UT\"\n\"KPA\",\"Keloids\",\"/gpfs/research/medicine/sequencer/NovaSeq/Outputs_fastq/2020_Outputs/Akash_Gunjan_05-19-2020_Yuna-samples/HISAT2/expression/stringtie/ref_only/KPA_UT\"\n\"P5\",\"Keloids\",\"/gpfs/research/medicine/sequencer/NovaSeq/Outputs_fastq/2020_Outputs/Akash_Gunjan_05-19-2020_Yuna-samples/HISAT2/expression/stringtie/ref_only/P5_UT\"\n\"P16\",\"Keloids\",\"/gpfs/research/medicine/sequencer/NovaSeq/Outputs_fastq/2020_Outputs/Akash_Gunjan_05-19-2020_Yuna-samples/HISAT2/expression/stringtie/ref_only/P16_UT\"\n\"P17\",\"Keloids\",\"/gpfs/research/medicine/sequencer/NovaSeq/Outputs_fastq/2020_Outputs/Akash_Gunjan_05-19-2020_Yuna-samples/HISAT2/expression/stringtie/ref_only/P17_UT\"\n\"P21\",\"Keloids\",\"/gpfs/research/medicine/sequencer/NovaSeq/Outputs_fastq/2020_Outputs/Akash_Gunjan_05-19-2020_Yuna-samples/HISAT2/expression/stringtie/ref_only/P21_UT\"\n\"P24\",\"Keloids\",\"/gpfs/research/medicine/sequencer/NovaSeq/Outputs_fastq/2020_Outputs/Akash_Gunjan_05-19-2020_Yuna-samples/HISAT2/expression/stringtie/ref_only/P24_UT\"\n" > Normal_vs_Keloids.csv

# UT vs. TA (Total)
printf "\"ids\",\"type\",\"path\"\n\"HDF1\",\"UT\",\"./HDF1_UT\"\n\"HDF2\",\"UT\",\"./HDF2_UT\"\n\"HDF3\",\"UT\",\"./HDF3_UT\"\n\"HDFPA\",\"UT\",\"./HDFPA_UT\"\n\"KPA\",\"UT\",\"./KPA_UT\"\n\"P5\",\"UT\",\"./P5_UT\"\n\"P16\",\"UT\",\"./P16_UT\"\n\"P17\",\"UT\",\"./P17_UT\"\n\"P21\",\"UT\",\"./P21_UT\"\n\"P24\",\"UT\",\"./P24_UT\"\n\"HDF1\",\"TA\",\"./HDF1_TA\"\n\"HDF2\",\"TA\",\"./HDF2_TA\"\n\"HDF3\",\"TA\",\"./HDF3_TA\"\n\"HDFPA\",\"TA\",\"./HDFPA_TA\"\n\"KPA\",\"TA\",\"./KPA_TA\"\n\"P5\",\"TA\",\"./P5_TA\"\n\"P16\",\"TA\",\"./P16_TA\"\n\"P17\",\"TA\",\"./P17_TA\"\n\"P21\",\"TA\",\"./P21_TA\"\n\"P24\",\"TA\",\"./P24_TA\"\n" > Total_UT_vs_TA.csv

# UT vs. TA (Normal)
printf "\"ids\",\"type\",\"path\"\n\"HDF1\",\"UT\",\"./HDF1_UT\"\n\"HDF2\",\"UT\",\"./HDF2_UT\"\n\"HDF3\",\"UT\",\"./HDF3_UT\"\n\"HDFPA\",\"UT\",\"./HDFPA_UT\"\n\"HDF1\",\"TA\",\"./HDF1_TA\"\n\"HDF2\",\"TA\",\"./HDF2_TA\"\n\"HDF3\",\"TA\",\"./HDF3_TA\"\n\"HDFPA\",\"TA\",\"./HDFPA_TA\"\n" > Normal_UT_vs_TA.csv

# UT vs. TA (Keloids)
printf "\"ids\",\"type\",\"path\"\n\"KPA\",\"UT\",\"./KPA_UT\"\n\"P5\",\"UT\",\"./P5_UT\"\n\"P16\",\"UT\",\"./P16_UT\"\n\"P17\",\"UT\",\"./P17_UT\"\n\"P21\",\"UT\",\"./P21_UT\"\n\"P24\",\"UT\",\"./P24_UT\"\n\"KPA\",\"TA\",\"./KPA_TA\"\n\"P5\",\"TA\",\"./P5_TA\"\n\"P16\",\"TA\",\"./P16_TA\"\n\"P17\",\"TA\",\"./P17_TA\"\n\"P21\",\"TA\",\"./P21_TA\"\n\"P24\",\"TA\",\"./P24_TA\"\n" > Keloids_UT_vs_TA.csv

# Resistant vs. Sensitive (UT)
printf "\"ids\",\"type\",\"path\"\n\"KPA\",\"Sensitive\",\"./KPA_UT\"\n\"P5\",\"Sensitive\",\"./P5_UT\"\n\"P16\",\"Resistant\",\"./P16_UT\"\n\"P17\",\"Sensitive\",\"./P17_UT\"\n\"P21\",\"Resistant\",\"./P21_UT\"\n\"P24\",\"Resistant\",\"./P24_UT\"\n" > Resistant_vs_Sensitive_UT.csv

# Resistant vs. Sensitive (TA)
printf "\"ids\",\"type\",\"path\"\n\"KPA\",\"Sensitive\",\"./KPA_TA\"\n\"P5\",\"Sensitive\",\"./P5_TA\"\n\"P16\",\"Resistant\",\"./P16_TA\"\n\"P17\",\"Sensitive\",\"./P17_TA\"\n\"P21\",\"Resistant\",\"./P21_TA\"\n\"P24\",\"Resistant\",\"./P24_TA\"\n" > Resistant_vs_Sensitive_TA.csv
